environment:
  global:
    JEST_JUNIT_OUTPUT: .\dist\js-test-results.xml
  matrix:
    # https://www.appveyor.com/docs/build-environment/#node-js
    - nodejs_version: Current
    - nodejs_version: LTS

install:
  - ps: Install-Product node $env:nodejs_version x64
  # https://www.appveyor.com/docs/build-environment/#tools
  # yarn is preinstalled on appveyor instances
  - yarn install --no-progress --frozen-lockfile

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn compile
  - yarn test:ci

on_success:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $($env:JEST_JUNIT_OUTPUT)))

build: off
shallow_clone: true
matrix:
  fast_finish: true

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'
