coverage:
  # strict_yaml_branch: master
  precision: 2
  round: down
  range: "70...90"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/node_modules/**",
  - "**/dist/**",
  - "**/build/**",
  - "**/generated/**"
  - "\\.(test|spec)\\.(jsx?|tsx?)$"
