dist: trusty
language: node_js
node_js:
  - "lts/*" # using the latest node LTS version
  - "node" # using the latest node stable version
env:
  # lint source code
  - YARN_COMMAND="lint"
  # ensure TS compiles
  - YARN_COMMAND="compile"
  # run unit tests
  #- YARN_COMMAND="yarn test"
  # create documentation
  #- YARN_COMMAND="yarn docs"
cache:
  yarn: true
before_install:
  # install the latest version of yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --no-progress --frozen-lockfile
script:
  # using env to run the commands in parallel
  - echo "Going to execute 'yarn $YARN_COMMAND'" && yarn $YARN_COMMAND
