dist: trusty
language: node_js
node_js:
  - "lts/*"
  - "9"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
env:
  # lint source code
  - COMMAND="yarn lint"
  # ensure TS compiles
  #- COMMAND="yarn compile"
  # run unit tests
  #- COMMAND="yarn test"
  # create documentation
  #- COMMAND="yarn docs"
script:
  # using env to run the commands in parallel
  - (eval "$COMMAND")
