dist: trusty
language: node_js
node_js:
  - "lts/*" # using the latest node LTS version
  - "node" # using the latest node stable version
env:
  # - YARN_COMMAND="lint" # TSLint is executed/checked via CodeClimate
  - YARN_COMMAND="compile" # check if the TS code compiles
  - YARN_COMMAND="test:ci" # check if the unit tests succeed
  #- YARN_COMMAND="docs" # create documentation
cache:
  yarn: true
before_install:
  # install the latest version of yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --no-progress --frozen-lockfile
script:
  # using env to run the commands in parallel
  - echo "Going to execute 'yarn $YARN_COMMAND'" && yarn $YARN_COMMAND
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
