version: 2

references:
  test_path: &test_path
    reports/junit
  defaults: &defaults
    working_directory: ~/repo
    environment:
      - JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
  defaults_node_lts: &defaults_node_lts
    <<: *defaults
    docker:
      - image: node:carbon # LTS 8
  defaults_node_stable: &defaults_node_stable
    <<: *defaults
    docker:
      - image: node:latest
  cache_key: &cache_key
    v3-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
  backup1_cache_key: &backup1_cache_key
    v3-dependencies-{{ .Branch }}-
  backup2_cache_key: &backup2_cache_key
    v3-dependencies-
  restore_dep_cache: &restore_dep_cache
    restore_cache:
      keys:
        - *cache_key
        - *backup1_cache_key
        - *backup2_cache_key
  save_dep_cache: &save_dep_cache
    save_cache:
      paths:
        - node_modules
      key: *cache_key
  default_steps: &default_steps
    - checkout
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: echo 'export PATH=$HOME/.yarn/bin:$PATH' >> $BASH_ENV
    - run: node --version && npm --version && yarn --version
    - *restore_dep_cache
    - run: yarn install --no-progress --frozen-lockfile
    - *save_dep_cache
    # - run: yarn lint # TSLint is executed/checked via CodeClimate
    - run: yarn compile # check if the TS code compiles
    - run: yarn test:ci # check if the unit tests succeed
    - store_test_results:
          path: *test_path
    - store_artifacts:
        path: *test_path
    - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  lint_step: &lint_step
    lint

jobs:
  node-lts:
    <<: *defaults_node_lts
    steps:
      *default_steps
  node-stable:
    <<: *defaults_node_stable
    steps:
      *default_steps

# to run multiple jobs in parallel
workflows:
  version: 2
  run_parallel:
    jobs:
      - node-lts
      - node-stable
