version: 2

references:
  base_container_config: &base_container_config
    working_directory: ~/repo
    parallelism: 2
    environment:
      - YARN_COMMANDS: lint compile
  node_lts_image: &node_lts_image
    image: circleci/node:carbon # LTS 8
  node_stable_image: &node_stable_image
    image: circleci/node:latest
  cache_key: &cache_key
    v1-dependencies-{{ checksum "yarn.lock" }}
  backup_cache_key: &backup_cache_key
    v1-dependencies-
  restore_dep_cache: &restore_dep_cache
    restore_cache:
      keys:
        - *cache_key
        - *backup_cache_key
  save_dep_cache: &save_dep_cache
    save_cache:
      paths:
        - node_modules
      key: *cache_key
  default_steps: &default_steps
    - checkout
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: echo 'export PATH=$HOME/.yarn/bin:$PATH' >> $BASH_ENV
    - run: node --version && npm --version && yarn --version
    - *restore_dep_cache
    - run: yarn install --no-progress
    - *save_dep_cache
    - run: YARN_COMMAND=$(circleci tests split $(echo $YARN_COMMANDS | tr " " "\n"))
    - run: echo "Going to execute 'yarn $YARN_COMMAND'" && yarn $YARN_COMMAND
  lint_step: &lint_step
    lint

jobs:
  node-lts:
    <<: *base_container_config
    docker:
      - *node_lts_image
    steps:
      *default_steps
  node-stable:
    <<: *base_container_config
    docker:
      - *node_stable_image
    steps:
      *default_steps

# to run multiple jobs in parallel
workflows:
  version: 2
  run_parallel:
    jobs:
      - node-lts
      - node-stable
