version: 2
jobs:
  build:
    docker:
      - image: node:carbon # LTS 8
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: export PATH="$HOME/.yarn/bin:$PATH"
      - run: node --version && npm --version && yarn --version
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
