/* tslint:disable */

/** THIS FILE IS AUTOGENERATED FROM THE UMS JSON SCHEMA FILES. DO NOT EDIT MANUALLY. */

import * as ConsumerRequests from "./consumer_requests";
import * as ConsumerResponses from "./consumer_responses";
import * as ConsumerNotifications from "./consumer_notifications";
import * as AgentResponses from "./agent_responses";
import * as AgentNotifications from "./agent_notifications";
import * as CommonUms from "./common_ums";

const merged = {...ConsumerRequests, ...ConsumerResponses, ...ConsumerNotifications, ...AgentResponses, ...AgentNotifications, ...CommonUms};
export default merged;
